name: open-geo-tutorial
channels:
  - conda-forge
dependencies:
  - rasterio 
  - matplotlib 
  - folium 
  - pyproj 
  - shapely 
  - notebook 
  - pandas 
  - fiona 
  - descartes 
  - cartopy 
  - scikit-learn 
  - geopandas 
  - rtree 
  - keras 
  - geojson